# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json
name: nodejs-aks-app-template
metadata:
    template: nodejs-web-aks-template@0.0.1-beta
infra:
    provider: "bicep"
    path: "infra"
    module: "main"
services:
    web:
        project: ./src/web # path to your web project
        dist: build # relative path to service deployment artifacts. The CLI will use files under this path to create the deployment artifact
        language: js  # one of the supported languages
        host: aks # deployment target
pipeline:
    provider: "github"
